language: python
dist: bionic
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -e .[tests,docs] tox-travis
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C .
matrix:
  include:
  - name: "3.9"
    python: 3.9
  - name: "3.10"
    python: 3.10
  - name: "3.11"
    python: 3.11
script: tox
after_success:
  - if [ "${TRAVIS_PYTHON_VERSION}" == "3.11" ];
    then ./coveralls report --repo-token=E8y6cerK5DVDZocB7eHTdzBKjdwQDkJzw;
    fi;
